language: bash
services: docker

env:
  - VERSION=1.25.0 VARIANT=stretch/slim
  - VERSION=1.25.0 VARIANT=stretch
  - VERSION=1.25.0 VARIANT=jessie

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION/$VARIANT"
  - slash='/'; image="rust:${VERSION}-${VARIANT//$slash/-}"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
