language: bash
services: docker

env:
#VERSIONS
  - VERSION=1.74.0 VARIANT=buster
  - VERSION=1.74.0 VARIANT=buster/slim
  - VERSION=1.74.0 VARIANT=bullseye
  - VERSION=1.74.0 VARIANT=bullseye/slim
  - VERSION=1.74.0 VARIANT=bookworm
  - VERSION=1.74.0 VARIANT=bookworm/slim
  - VERSION=1.74.0 VARIANT=alpine3.17
  - VERSION=1.74.0 VARIANT=alpine3.18
#VERSIONS

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION/$VARIANT"
  - slash='/'; image="rust:${VERSION}-${VARIANT//$slash/-}"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
