name: CI

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
#RUST_VERSION
      RUST_VERSION: 1.83.0
#RUST_VERSION
    strategy:
      matrix:
        include:
#VERSIONS
          - name: bullseye
            variant: bullseye
          - name: slim-bullseye
            variant: bullseye/slim
          - name: bookworm
            variant: bookworm
          - name: slim-bookworm
            variant: bookworm/slim
          - name: alpine3.19
            variant: alpine3.19
          - name: alpine3.20
            variant: alpine3.20
#VERSIONS
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v4
      - run: git clone https://github.com/docker-library/official-images.git ~/official-images
      - run: docker build -t rust:$RUST_VERSION-${{ matrix.name }} stable/${{ matrix.variant }}
      - run: ~/official-images/test/run.sh rust:$RUST_VERSION-${{ matrix.name }}
      - run: docker images
